variables:
  PLUGIN_VERSION: "0.2.0"

stages:
  - test
  - check
  - build
  - deploy
  - qa
  - release

include:
  - /.gitlab-ci-test.yml
  - /.gitlab-ci-build.yml
  - /.gitlab-ci-deploy.yml
  - /.gitlab-ci-qa.yml
  - /.gitlab-ci-release.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  # TODO BUG  FIXED / Remove Code Quality LONG  
  #- template: Code-Quality.gitlab-ci.yml
  #- template: Security/Container-Scanning.gitlab-ci.yml
  #- template: DAST.gitlab-ci.yml

sast:
  stage: test
