variables:
  PLUGIN_VERSION: "0.4.3"

stages:
  - test
  - check
  - build
  - release
  - package
  - upload
  - deploy
  - qa

include:
  # BRANCH
  - /tools/gitlab/test.yml
  - /tools/gitlab/build.yml
  - /tools/gitlab/linux.yml
  # MASTER
  - /tools/gitlab/release.yml
  # TAGS
  - /tools/gitlab/package.yml
  - /tools/gitlab/upload.yml
  # MR
  - /tools/gitlab/deploy.yml
  - /tools/gitlab/qa.yml
  # SHED && MR
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  # TODO LOW / New features / Remove Code Quality / TOO LONG  
  #- template: Code-Quality.gitlab-ci.yml
  #- template: Security/Container-Scanning.gitlab-ci.yml
  #- template: DAST.gitlab-ci.yml

sast:
  stage: test

secret_detection:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: '$CI_PIPELINE_SOURCE == "schedule"'


flawfinder-sast:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

