
.code: &code
  artifacts:
    expire_in: 1 week
    name: "Plugin"
    paths:
      - lin.xpl
      - mac.xpl
      - win.xpl
      - check_mac64_intel
      - check_lin64_amd64
      - check.exe
  before_script:
    - cp -r ~/SDK ./
    - cp -r ~/hidapi ./
  only:
    - merge_requests
    - branches	
    - tags
  except:
    - master
    - schedules
  stage: build

build:plugin:linux:
  <<: *code
  image: tarasmal/saitek:cmake
  script:
    - cmake CMakeLists.txt -DXPVERSION="${PLUGIN_VERSION}_${CI_COMMIT_SHORT_SHA}" -DXPLANE11PLUGIN=true
    - make
  tags: [linux]

build:check:linux:
  <<: *code
  image: tarasmal/saitek:cmake
  script:
    - cmake CMakeLists.txt -DXPVERSION="${PLUGIN_VERSION}_${CI_COMMIT_SHORT_SHA}" 
    - make
  tags: [linux]

build:plugin:mac:
  <<: *code
  script:
    - cmake CMakeLists.txt -DXPVERSION="${PLUGIN_VERSION}_${CI_COMMIT_SHORT_SHA}" -DXPLANE11PLUGIN=true
    - make
  tags: [mac]
  except: []

build:check:mac:
  <<: *code
  script:
    - cmake CMakeLists.txt -DXPVERSION="${PLUGIN_VERSION}_${CI_COMMIT_SHORT_SHA}"
    - make
  tags: [mac]

build:windows:
  <<: *code
  script:
    - msbuild saitek.sln /p:Configuration=Release
    - cp Release\plugins\saitek\64\win.xpl ./
  tags: [win10]
  except: []
