
.code: &code
  artifacts:
    expire_in: 1 week
    name: "Plugin"
    paths:
      - lin.xpl
      - mac.xpl
      - win.xpl
  before_script:
    - cp -r ~/SDK ./
    - cp -r ~/hidapi ./

build:linux:
  <<: *code
  stage: build
  image: tarasmal/saitek:cmake
  script:
    - cmake CMakeLists.txt -DXPVERSION="${PLUGIN_VERSION}_${CI_COMMIT_SHORT_SHA}" -DXPLANE11PLUGIN=true
    - make
  tags: [linux]

build:mac:
  <<: *code
  stage: build
  script:
    - cmake CMakeLists.txt -DXPVERSION="${PLUGIN_VERSION}_${CI_COMMIT_SHORT_SHA}" -DXPLANE11PLUGIN=true
    - make
  tags: [mac]

build:windows:
  <<: *code
  stage: build
  script:
    - msbuild saitek.sln /p:Configuration=Release
    - cp Release\plugins\saitek\64\win.xpl ./
  tags: [win10]
