
package:
  artifacts:
    expire_in: 1 week
    name: "Plugin"
    paths:
      - plugin.zip
      - win10.zip
      - lin.zip
      - mac.zip
  stage: package
  image: tarasmal/saitek:cmake
  script:
    - mkdir -p 64
    - cp win.xpl 64/win.xpl
    - cp mac.xpl 64/mac.xpl
    - cp lin.xpl 64/lin.xpl
    - zip  plugin.zip -r config/ 64/ check*
    - zip  win10.zip -r config/ 64/win.xpl
    - zip  lin.zip -r config/ 64/lin.xpl check_lin64_amd64
    - zip  mac.zip -r config/ 64/mac.xpl check_mac64_intel
  dependencies:
    - build:plugin:linux
    - build:check:linux
    - build:plugin:mac
    - build:check:mac
    - build:windows
  only:
    - tags
